### ISSUE TITLE
Does not work with latest [ 1.47.0] VS Code

### ISSUE THREAD

**Issue by kittaakos** [octref/vscode-electron-debug#17]
I have been using my launch config for years now, unfortunately, debugging an electron app started to fail with the latest VS Code.

Steps to reproduce:
```
akos.kitta@Akoss-MacBook-Pro Desktop % git clone https://github.com/octref/vscode-electron-debug.git
Cloning into 'vscode-electron-debug'...
remote: Enumerating objects: 101, done.
remote: Total 101 (delta 0), reused 0 (delta 0), pack-reused 101
Receiving objects: 100% (101/101), 50.26 KiB | 402.00 KiB/s, done.
Resolving deltas: 100% (46/46), done.
akos.kitta@Akoss-MacBook-Pro Desktop % cd vscode-electron-debug/electron-quick-start
akos.kitta@Akoss-MacBook-Pro electron-quick-start % yarn 
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 2.96s.
akos.kitta@Akoss-MacBook-Pro electron-quick-start % code .
akos.kitta@Akoss-MacBook-Pro electron-quick-start % 
```

And launch the `Debug Main Process` config.

Error:
```
/Users/akos.kitta/Desktop/vscode-electron-debug/electron-quick-start/node_modules/.bin/electron /Users/akos.kitta/Desktop/vscode-electron-debug/electron-quick-start/main.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '"/Applications/Visual'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:824:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Process exited with code 1
```

Note: on my system (macOS), VS Code installed to `/Applications/Visual Studio Code.app`.

VS Code version:
```
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z (5 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**Comment by kittaakos** [comment]
Seem to be this: https://github.com/microsoft/vscode/issues/102035#issuecomment-656801666

I am going to check it and update this thread.

**Comment by kittaakos** [comment]
> I am going to check it and update this thread.

Confirmed, there is a workaround. In my case, the easiest way was to set  the `debug.javascript.usePreview` preference to `false`.

From the UI it looks like this:

![Screen Shot 2020-07-14 at 10 40 26](https://user-images.githubusercontent.com/1405703/87404586-9c99ba80-c5be-11ea-8460-a6b21ac3fb2a.jpg)

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!
